좋아요. 시작합시다, 여러분. 좋은 오후입니다. 60001의 두 번째 강의와 600의 두 번째 강의에 오신 것을 환영합니다. 그러니 언제나 그렇듯이 강의를 따라가고 싶으시면 매 수업 최소 한 시간 전에 제가 제공할 슬라이드와 코드를 다운로드하시기 바랍니다.

그럼 지난번에 우리가 한 일을 간단히 요약해 보겠습니다. 지난번에 우리는 컴퓨터가 무엇인지에 대해 조금 이야기했습니다. 그리고 지난 강의의 주요 내용은 실제로 컴퓨터는 명령받은 대로만 수행한다는 것입니다. 그렇죠? 그래서 자발적으로 스스로 결정을 내리지는 않을 것입니다. 프로그래머로서 당신은 프로그램을 작성함으로써 당신이 원하는 것이 무엇인지 말해야 합니다. 좋아요. 그래서 우리는 간단한 객체에 대해 이야기했습니다. 그리고 이 물건들은 종류가 달랐습니다. 그래서 우리는 정수, 부동소수점, 부울을 보았습니다. 그런 다음 우리는 그들과 함께 몇 가지 간단한 작업을 수행했습니다.

오늘 우리는 문자열이라는 새로운 유형의 개체를 살펴보겠습니다. 그런 다음 프로그래밍 도구 상자에 더욱 강력한 기능을 소개하겠습니다. 그래서 우리는 프로그램 내에서 분기하는 방법과 작업을 만드는 방법, 즉 프로그램 내에서 컴퓨터가 특정 작업을 반복하도록 만드는 방법을 살펴보겠습니다.

== STRINGS

* 문자, 특수 문자, 빈칸, 숫자
* 따옴표(quotation marks) 또는 작은 따옴표(single quotes)로 싸임 +
h1 = "hello there"
* 문자열 접합 +
name = "ana"
greet = hi + name
greeting = hi = " " + name

* Python 문서에 정의된 대로 문자열에 대해 일부 작업을 수행 +
silly = hi + " " + name * 3

좋아요. 그럼 문자열부터 살펴보겠습니다. 따라서 문자열은 새로운 객체 유형입니다. 지금까지 우리는 정수인 정수, 소수인 부동 소수점, 참과 거짓인 부울을 보았습니다. 따라서 문자열은 문자의 시퀀스가 됩니다. 그리고 이 캐릭터는 무엇이든 될 수 있습니다. 문자, 숫자, 특수 문자 및 공백이 될 수 있습니다. 그리고 문자열 객체를 따옴표로 묶어서 Python에 대해 이야기하고 있음을 알립니다. 따라서 이 경우 값이 h-e-l-l-o space t-h-e-r-e인 객체를 생성합니다.

그리고 Python은 그것이 문자열 객체라는 것을 알고 있습니다. 왜냐하면 우리가 그것을 따옴표로 묶었기 때문입니다. 큰따옴표일 수도 있고 작은따옴표일 수도 있지만 일관성을 유지한다면 문제가 되지 않습니다. 그리고 이 객체를 hi라는 변수에 바인딩합니다. 그리고 우리는 할당 연산자인 등호를 사용하여 이를 사용하고 있습니다. 따라서 이제부터 우리가 이 변수 hi를 참조할 때마다 Python은 '아, 값이 무엇인지 알아요. 문자열입니다'라고 말할 것입니다.

그래서 오늘은 문자열에 대해 할 수 있는 두 가지 작업, 즉 두 가지 작업에 대해 알아보겠습니다. 하나는 그것들을 연결하는 것입니다. 그리고 연결은 실제로 이 더하기 연산자를 사용하기 위한 멋진 단어일 뿐입니다. 즉, 문자열을 하나로 묶는 것을 의미합니다. 그래서 hi라는 원래 변수가 있고 name이라는 새 변수를 만듭니다. 그리고 그 안에서 변수 이름에 문자열 a-n-a를 할당하겠습니다. 그리고 hi와 name, 두 변수 사이에 더하기 연산자를 사용하면 Python은 이 두 변수의 값을 보고 그냥 합치게 됩니다.

좋아요. Spider로 옮깁니다. 이것은 슬라이드에 나온 예일 뿐입니다. 그럼 무슨 일이 일어나는지 봅시다. 그래서 변수 hi, 변수 이름이 있고 이 둘을 함께 연결하는 것뿐입니다. 그런 다음 그것을 인쇄해 보겠습니다. 따라서 코드를 실행하면 "hello Thereana"가 인쇄되는 것을 볼 수 있습니다. 공간이 없습니다. 그리고 연결 연산자인 더하기가 암시적으로 공백을 추가하지 않기 때문에 공백이 없습니다. 다시 한 번, 컴퓨터가 지시한 대로만 수행하는 또 다른 예입니다. 공백을 추가하려면 실제로 수동으로 공백을 삽입해야 합니다. 이것이 바로 8번째 줄입니다. 그리고 이 줄에서는 변수 hi의 값을 공백과 연결합니다. 따옴표 안에 넣었다는 점에 주목하세요. 그냥 공간. 그리고 이름으로.

따라서 해당 값을 인쇄해 보면 이것이 거기에 있는 쓰레기 인사라는 것을 알 수 있습니다. 이제 우리는 제대로 된 인사를 하게 됐죠? 이것이 바로 문자열 간의 연결입니다.

그리고 문자열과 관련하여 우리가 살펴볼 또 다른 것은 star operator입니다. 이것이 여기 10행에 있는 것입니다. 따라서 Python에서는 문자열과 숫자 사이에 곱셈을 나타내는 star operator를 사용할 수 있습니다. 그리고 그렇게 하면 Python은 해당 문자열을 해당 횟수만큼 반복하는 것으로 해석합니다. 따라서 이 경우에는 우스꽝스러운 인사말을 만들고 "안녕하세요"인 hi 값을 공백과 이름을 연결합니다. 여기서 주목하세요. 저는 괄호를 사용하여 Python에게 이 연산을 먼저 수행한 다음 그 결과에 3을 곱하라고 지시합니다. 따라서 이를 인쇄하면 공백에 제 이름이 3배로 곱해지고, 그것은 "hello there"와 연결될 것입니다. 그래서 그것이 바로 거기에 print된 것입니다.

지난 강의에서 우리는 print에 관해 조금 이야기를 나누었습니다. 오늘은 print와 관련된 몇 가지 뉘앙스에 대해 이야기해보겠습니다. 따라서 인쇄를 사용하여 사용자와 상호 작용합니다. 사용자에게 내용을 인쇄하는 프로그램을 작성하는 것은 멋진 일입니다. 여기서 핵심 단어는 print입니다. 그리고 print 후에 괄호를 넣습니다. 그리고 괄호 안에는 사용자에게 보여주고 싶은 내용을 입력합니다.

그래서 이 작은 프로그램에서 저는 x라는 변수를 만들었습니다. 값 1을 할당한 다음 1을 인쇄합니다. 여기서는 캐스팅 중입니다. 그래서 저는 숫자 1, 즉 정수 1을 취하고 그것을 문자열로 캐스팅할 것입니다. 잠시 후에 그 이유를 알게 될 것입니다.

== INPUT/OUTPUT: print

* 콘솔로 무언가를 내보낼 때 사용
* 키워드는 **print**

[source, python]
----
x = 1
print(x)
x_str = str(x)
print("my fav num is", x, ".", "x = ", x)
print("my fav num is" + x_str + :". " "x = " + x_str)
----

그래서 저는 여기서 몇 가지 사실을 여러분께 알려드리고 싶습니다. 그래서 첫 번째 print에서는 여기저기서 쉼표를 사용하고 있습니다. 그리고 두 번째 print에서는 플러스를 사용하고 있습니다. 따라서 정의에 따르면 print 내부에 쉼표를 사용할 수 있습니다. print의 괄호 안에. 그리고 쉼표를 사용하면 Python은 쉼표가 있는 두 값 사이에 자동으로 공백을 추가합니다. 그래서 "my fav num is"이 첫 번째입니다. 두 번째는 쉼표 뒤에 오는 것입니다. x를 봅시다. 따라서 쉼표를 사용하면 Python이 자동으로 공백을 삽입합니다.

때로는 원할 수도 있고 그렇지 않을 수도 있습니다. 이를 원하지 않으면 연결 작업인 플러스를 사용할 수 있습니다. 그리고 작은 조각들을 모두 더해 하나의 큰 끈을 만들 수 있습니다. 쉼표를 사용하는 경우 항목, 즉 쉼표 사이에 있는 개체가 모두 문자열일 필요는 없습니다. 이것이 쉼표를 사용하는 것의 장점입니다. 하지만 단점은 곳곳에 공간이 있다는 것입니다. 더하기 연산자를 사용하면 Python이 지시한 대로 정확하게 수행하지만 모든 것이 문자열 객체여야 한다는 장점이 있습니다. 따라서 "my fav num is"는 문자열 객체입니다. 모든 숫자를 문자열 객체 등으로 변환해야 합니다.

따라서 Spider를 보면... 이것은 동일합니다. 거의 동일한 코드입니다. 그래서 여기에는 어디에도 공백이 없습니다. 여기 첫 번째 줄의 모든 곳에 쉼표가 있는 것을 볼 수 있습니다. 그래서 print하는 모든 항목 사이에 공백을 두겠습니다. 여기 이 줄은 일종의 쉼표와 연결의 조합입니다. 그래서 쉼표를 어디에 사용하느냐에 따라 여분의 공간이 생기게 됩니다. 그리고 여기 이 줄은 어디에서나 연결되어 있습니다. 따라서 이것을 실행하면 첫 번째 줄에 모든 개체 사이의 모든 곳에 공백이 추가되는 것을 볼 수 있습니다. 두 번째는 어딘가에 공백을 추가했습니다. 그리고 공백이 추가된 위치를 추적하여 정확히 확인할 수 있습니다. 그리고 여기 마지막 줄에는 어디에도 공백이 추가되지 않았습니다.

== INPUT/OUTPUT: input("")

* 따옴표 안이 있는 무엇이든 출력
* 사용자가 무언가를 입력하고 Enter를 누르는 경우
* 해당 값을 변수에 할당

[source, python]
----
text = input("Type anything...")
print(5 * text)
----

* input은 string을 주므로 숫자로 작업할 경우 반드시 변환해야 함

[source, python]
----
num = int(input("Type a number... "))
print(5 * text)
----

바로 여기 이 줄에서 사용자가 입력하는 것은 무엇이든 문자열이 됩니다. 그리고 우리는 해당 문자열 개체를 text라는 변수에 바인딩할 것입니다. 이제 내 프로그램에서 이 가변 텍스트를 사용하여 원하는 모든 작업을 수행할 수 있습니다. 이 경우에는 5 * text를 print합니다. 예를 들어 사용자가 "ha"를 입력했다면 "ha"를 5번 인쇄하겠습니다. 사용자가 나에게 5를 줬다면 그 사용자는 무엇이라고 생각합니까? 무엇이 인쇄될 것이라고 생각합니까? 25번 아니면 5번? 엄청난. 예. 정확히. 5 다섯 번.

따라서 콘솔에 내용을 인쇄하는 것도 좋지만 대화형 프로그램 작성의 두 번째 부분은 사용자로부터 입력을 받는 것입니다. 그리고 그것이 더 흥미로운 부분입니다. 따라서 문제 세트 0을 완료했다면 이미 스스로 이해하려고 노력했을 수도 있습니다. 하지만 여기 있습니다. 따라서 사용자로부터 입력을 받는 방법은 입력이라는 명령 기능을 사용하는 것입니다. 그리고 괄호 안에는 사용자에게 표시할 내용을 입력합니다. 따라서 이 예에서는 입력이 있고 여기서는 "아무거나 입력하세요"라고 말했습니다. 그래서 사용자는 여기에서 이 텍스트를 보게 될 것이고, 그러면 프로그램은 멈출 것입니다. 그리고 사용자가 무언가를 입력하고 Enter 키를 누를 때까지 기다립니다. 사용자가 Enter 키를 입력하자마자 사용자가 입력하는 내용은 모두 string이 됩니다. 예를 들어, 사용자가 숫자를 입력하면 해당 숫자의 string이 됩니다. 따라서 사용자가 입력하는 모든 내용은 string로 만들어집니다.

숫자를 문자열로 사용하고 싶지 않은 경우가 많습니다. 그렇죠? 숫자를 숫자로 작업하고 싶죠? 그래서 캐스팅을 해야 합니다. 그리고 우리는 마지막 강의를 배웠습니다. 입력 바로 앞에 이 작은 비트를 넣으면 캐스팅됩니다. 그리고 원하는 유형으로 캐스팅할 수 있습니다. 여기서는 int로 캐스팅했지만 부동 소수점으로 작업하려는 경우 float으로 캐스팅할 수도 있습니다. 그리고 이는 Python이 변환하는 방법을 알고 있는 숫자인 한 사용자가 입력한 모든 것을 숫자 자체로 변환합니다. 따라서 이 경우 사용자가 5를 주면 5를 5번 print하는 대신 5 *5를 print합니다. 이것이 바로 여기에 있는 코드입니다.

첫 번째 부분은 사용자가 무엇이든 입력하도록 하고 555를 입력하는 것입니다. 그런 다음 숫자를 입력할 때 숫자를 캐스팅하므로 연산을 수행합니다. 번호와 함께. 네, 질문입니다.

왜 캐스팅하고 싶으신가요?-- 아. 문제는 왜 문자열로 캐스팅하고 싶습니까? 왜 문자열을 숫자로 변환하고 싶나요?

아, Python은 항상-- 기본적으로 무엇을 입력하든 입력 명령의 정의에 따라 Python은 항상 이를 문자열로 만듭니다. 따라서 숫자로 작업하려면 명시적으로 말해야 합니다. 나는 숫자로 작업할 것입니다. 따라서 숫자 5를 지정하더라도 문자열 5라고 생각하게 됩니다. 네. 이것이 바로 입력이 작동하는 방식입니다.

== int, float, string 비교 연산

* i와 j는 변수 이름
* 아래 연산들은 Boolean으로 계산됨

[source, python]
----
i > j
i >= j
i < j
i <= j
i == j
i != j
----

다음으로 살펴볼 것은 코드에 테스트를 추가할 수 있는 방법입니다. 그리고 코드에 테스트를 추가하기 전에 실제 테스트를 수행할 수 있어야 합니다. 그래서 이것이 비교 연산자가 들어오는 곳입니다. 따라서 여기서는 i와 j가 변수라고 가정해 보겠습니다. 다음 비교는 Boolean을 제공합니다. 그래서 이것은 사실이거나 거짓이라고 말할 것입니다. 이것이 바로 여러분의 시험이 될 것입니다.

따라서 i와 j가 변수인 경우 int와 int, float와 float, 문자열과 문자열을 비교할 수 있습니다. 그리고 int와 float를 서로 비교할 수는 있지만 문자열을 숫자와 비교할 수는 없습니다. 사실, Python에서 그렇게 하려고 한다면 -- 여기 Spider에서 제가 말하려고 하면, 문자가 5보다 큰가요? 여기서 angry text를 받았습니다. 그리고 이것은 Python이 다음의 의미를 이해하지 못한다는 것을 의미합니다. 문자열을 숫자와 어떻게 비교합니까?

좋아요. 따라서 수학에서와 마찬가지로 이러한 일반적인 비교를 수행할 수 있습니다. 어떤 것이 어떤 것보다 크거나, 크거나 같거나, 작거나, 작거나 같다고 말할 수 있습니다. 저는 여러분의 동등(equality)에 주목하고 싶습니다. 따라서 단일 등호는 할당입니다. 따라서 값을 가져와 변수에 할당합니다. 하지만 이중 등호를 사용하는 경우 이는 동등성을 테스트하는 것입니다. 변수 i의 값은 변수 j의 값과 동일합니까? 그리고 그것은 또한 여러분에게 참 또는 거짓이라는 불리언을 제공할 것입니다. 또한 느낌표 같음을 사용하여 부등식을 테스트할 수도 있습니다. 즉, 변수 i의 값이 변수 j의 값과 같지 않습니까? 그렇다면 참이고, 그렇지 않으면 거짓입니다.

좋아요. 이제 우리는 논리적인.. 질문이 있네요.

네, 좋은 질문이에요. 그렇다면 문자열을 보다 큰 문자열과 비교한다는 것은 무엇을 의미할까요? 그래서 그것은 단지 그것들을 사전식으로 비교할 것입니다. 그럼 알파벳에서 먼저 나오나요? 그래서 우리는 그것을 테스트할 수도 있습니다. a가 b보다 크다고 말할 수 있나요? 그리고 그것은 거짓입니다. 따라서 b는 a보다 알파벳 늦게 옵니다.

좋아요. 이제 테스트를 수행할 수 있는 방법이 생겼습니다. 이제 테스트를 수행할 수 있는 방법이 있으므로 프로그래밍 도구 상자에 몇 가지 분기를 추가할 수 있습니다. MIT의 지도입니다. 우리 코드에서 분기를 수행하려는 이유를 설명하기 위해 일종의 작은 예를 살펴보겠습니다. 그리고 이 강의가 끝나면 여러분은 제가 설명할 알고리즘을 일종의 코드화할 수 있을 것이라고 생각합니다. 그래서 우리 대부분은 MIT를 미로로 봅니다. 여기 왔을 때 처음으로 그랬어요. 제가 처음 여기에 왔을 때 당연히 무료 음식 메일링 리스트에 가입했습니다. 그리고 MIT는 미로이기 때문에 어디로 가야할지, 무료 음식을 얻는 최단 경로가 무엇인지 전혀 몰랐습니다. 그래서 그것에 대해 생각하는 한 가지 방법은 제가 하고 싶었던 전부는 무료 음식을 얻는 것이었습니다.