좋아요. 시작합시다, 여러분. 좋은 오후입니다. 60001의 두 번째 강의와 600의 두 번째 강의에 오신 것을 환영합니다. 그러니 언제나 그렇듯이 강의를 따라가고 싶으시면 매 수업 최소 한 시간 전에 제가 제공할 슬라이드와 코드를 다운로드하시기 바랍니다.

그럼 지난번에 우리가 한 일을 간단히 요약해 보겠습니다. 지난번에 우리는 컴퓨터가 무엇인지에 대해 조금 이야기했습니다. 그리고 지난 강의의 주요 내용은 실제로 컴퓨터는 명령받은 대로만 수행한다는 것입니다. 그렇죠? 그래서 자발적으로 스스로 결정을 내리지는 않을 것입니다. 프로그래머로서 당신은 프로그램을 작성함으로써 당신이 원하는 것이 무엇인지 말해야 합니다. 좋아요. 그래서 우리는 간단한 객체에 대해 이야기했습니다. 그리고 이 물건들은 종류가 달랐습니다. 그래서 우리는 정수, 부동소수점, 부울을 보았습니다. 그런 다음 우리는 그들과 함께 몇 가지 간단한 작업을 수행했습니다.

오늘 우리는 문자열이라는 새로운 유형의 개체를 살펴보겠습니다. 그런 다음 프로그래밍 도구 상자에 더욱 강력한 기능을 소개하겠습니다. 그래서 우리는 프로그램 내에서 분기하는 방법과 작업을 만드는 방법, 즉 프로그램 내에서 컴퓨터가 특정 작업을 반복하도록 만드는 방법을 살펴보겠습니다.

== STRINGS

* 문자, 특수 문자, 빈칸, 숫자
* 따옴표(quotation marks) 또는 작은 따옴표(single quotes)로 싸임 +
h1 = "hello there"
* 문자열 접합 +
name = "ana"
greet = hi + name
greeting = hi = " " + name

* Python 문서에 정의된 대로 문자열에 대해 일부 작업을 수행 +
silly = hi + " " + name * 3

좋아요. 그럼 문자열부터 살펴보겠습니다. 따라서 문자열은 새로운 객체 유형입니다. 지금까지 우리는 정수인 정수, 소수인 부동 소수점, 참과 거짓인 부울을 보았습니다. 따라서 문자열은 문자의 시퀀스가 됩니다. 그리고 이 캐릭터는 무엇이든 될 수 있습니다. 문자, 숫자, 특수 문자 및 공백이 될 수 있습니다. 그리고 문자열 객체를 따옴표로 묶어서 Python에 대해 이야기하고 있음을 알립니다. 따라서 이 경우 값이 h-e-l-l-o space t-h-e-r-e인 객체를 생성합니다.

그리고 Python은 그것이 문자열 객체라는 것을 알고 있습니다. 왜냐하면 우리가 그것을 따옴표로 묶었기 때문입니다. 큰따옴표일 수도 있고 작은따옴표일 수도 있지만 일관성을 유지한다면 문제가 되지 않습니다. 그리고 이 객체를 hi라는 변수에 바인딩합니다. 그리고 우리는 할당 연산자인 등호를 사용하여 이를 사용하고 있습니다. 따라서 이제부터 우리가 이 변수 hi를 참조할 때마다 Python은 '아, 값이 무엇인지 알아요. 문자열입니다'라고 말할 것입니다.

그래서 오늘은 문자열에 대해 할 수 있는 두 가지 작업, 즉 두 가지 작업에 대해 알아보겠습니다. 하나는 그것들을 연결하는 것입니다. 그리고 연결은 실제로 이 더하기 연산자를 사용하기 위한 멋진 단어일 뿐입니다. 즉, 문자열을 하나로 묶는 것을 의미합니다. 그래서 hi라는 원래 변수가 있고 name이라는 새 변수를 만듭니다. 그리고 그 안에서 변수 이름에 문자열 a-n-a를 할당하겠습니다. 그리고 hi와 name, 두 변수 사이에 더하기 연산자를 사용하면 Python은 이 두 변수의 값을 보고 그냥 합치게 됩니다.

