= Python Tutorial: 소개

Python은 배우기 쉬우면서도 강력한 프로그래밍 언어입니다. 효율적인 자료구조와 객체지향 프로그래밍에 대한 간단하고도 효율적인 접근법을 제공합니다. Python은 우아한 문법과 dynamic typing을 지원하는 인터프리터 언어로서, 대부분의 플랫폼과 문제 영역에서 스크립트 작성과 빠른 응용 프로그램 개발에 이상적인 환경을 제공합니다.

Python 인터프리터와 광범위한 표준 라이브러리는 http://www.python.org[Python 웹 사이트]에서 주요 플랫폼에 대한 소스코드 또는 바이너리 형식으로 제공되며 자유롭게 배포할 수 있습니다. Python 웹 사이트에는 무료로 제공되는 많은 서드파티 Python 모듈, 추가 문서들이 제공됩니다.

Python 인터프리터는 C, C++(또는 C에서 호출 가능한 다른 언어들)로 구현된 새 함수나 자료구조를 쉽게 추가할 수 있습니다. 파이썬은 응용 프로그램을 위한 확장 언어로도 적합합니다. 

이 학습서는 Python 언어와 시스템의 기본 개념과 기능들을 격식없이 소개합니다. Python 인터프리터를 직접 만져볼 수 있도록 과정을 제곻하지만, 모든 예제가 독립적으로 구성되어 오프라인에서 읽기에도 적합합니다.

표준 객체들과 모듈들에 대한 설명은 https://docs.python.org/ko/3/library/index.html#library-index[Python 표준 라이브러리]를 참조합니다. Python 언어에 대한 문법, 개념 레퍼런스는 https://docs.python.org/ko/3/reference/index.html#reference-index[파이썬 언어 레퍼런스]를 참조합니다. C나 C++등 다른 언어로 확장하려면 https://docs.python.org/ko/3/extending/index.html#extending-index[Python 인터프리터 확장 및 내장]와 https://docs.python.org/ko/3/c-api/index.html#c-api-index[Python/C 레퍼런스 설명서] 참고할 수 있습니다.

이 학습서는 Python의 모든 것을 다루지 않습니다. 심지어는 자주 사용되는 기능조차도 다루지 않습니다. 대신에, Python의 가장 주목할만한 기능들을 소개하고, 언어의 컨셉과 스타일에 대한 전반적인 내용들을 제공합니다. 이 학습서를 모두 읽었다는 것은 https://docs.python.org/ko/3/library/index.html#library-index[Python 표준 라이브러리]에 기술된 다양한 Python 라이브러리 모듈들에 대해 학습할 수 있는 준비가 되었다는 것을 의미합니다.

학습 도중 익숙하지 않은 용어에 대해서는 https://docs.python.org/ko/3/glossary.html#glossary[용어집]을 참조합니다.

++++
<style>
ol {
  list-style-type: none;
  counter-reset: item;
  margin: 0;
  padding: 0;
}

ol > li {
  display: table;
  counter-increment: item;
  margin-bottom: 0.6em;
}

ol > li:before {
  content: counters(item, ".") ". ";
  display: table-cell;
  padding-right: 0.6em;
}

li ol > li {
  margin: 0;
}

li ol > li:before {
  content: counters(item, ".") " ";
}
</style>
++++

. link:./01_Whetting_Your_Appetite.adoc[학습 의욕 고취]
. link:./02_using_the_python_interpreter.adoc[파이썬 인터프리터 사용하기]
.. 인터프리터 실행하기
... 인자 전달
... 대화형 모드
.. 인터프리터와 환경
... 소스 코드 인코딩
. link:./03_an_informal_introduction_to_python.adoc[파이썬의 간략한 소개]
.. 파이썬을 계산기로 사용하기
... 숫자
... 텍스트
... 리스트
.. 프로그래밍으로의 첫걸음
. 기타 제어 흐름 도구
.. if 문
.. for 문
.. range() 함수
.. 루프의 break 와 continue 문, 그리고 else 절
.. pass 문
.. match진술
.. 함수 정의하기
.. 함수 정의 더 보기
... 기본 인자 값
... 키워드 인자
... 특수 매개 변수
.... 위치-키워드(Positional-or-Keyword) 인자
.... 위치 전용 매개 변수
.... 키워드 전용 인자
.... 함수 예제
.... 복습
... 임의의 인자 목록
... 인자 목록 언 패킹
... 람다 표현식
... 도큐멘테이션 문자열
... 함수 어노테이션
.. 막간극: 코딩 스타일
. 자료 구조
.. 리스트 더 보기
... 리스트를 스택으로 사용하기
... 리스트를 큐로 사용하기
... 리스트 컴프리헨션
... 중첩된 리스트 컴프리헨션
.. del 문
.. 튜플과 시퀀스
.. 집합
.. 딕셔너리
.. 루프 테크닉
.. 조건 더 보기
.. 시퀀스와 다른 형들을 비교하기
. 모듈
.. 모듈 더 보기
... 모듈을 스크립트로 실행하기
... 모듈 검색 경로
... “컴파일된” 파이썬 파일
.. 표준 모듈들
.. dir() 함수
.. 패키지
... 패키지에서 * 임포트 하기
... 패키지 내부 간의 참조
... 여러 디렉터리에 있는 패키지
. 입력과 출력
.. 장식적인 출력 포매팅
... 포맷 문자열 리터럴
... 문자열 format() 메서드
... 수동 문자열 포매팅
... 예전의 문자열 포매팅
.. 파일을 읽고 쓰기
... 파일 객체의 매소드
... json 으로 구조적인 데이터를 저장하기
. 에러와 예외
.. 문법 에러
.. 예외
.. 예외 처리하기
.. 예외 일으키기
.. 예외 연쇄
.. 사용자 정의 예외
.. 뒷정리 동작 정의하기
.. 미리 정의된 뒷정리 동작들
.. 관련되지 않은 여러 예외 발생 및 처리
.. 메모로 예외 강화
. 클래스
.. 이름과 객체에 관한 한마디
.. 파이썬 스코프와 이름 공간
..1. 스코프와 이름 공간 예
.. 클래스와의 첫 만남
... 클래스 정의 문법
... 클래스 객체
... 인스턴스 객체
... 메서드 객체
... 클래스와 인스턴스 변수
.. 기타 주의사항들
.. 상속
..1. 다중 상속
.. 비공개 변수
.. 잡동사니
.. 이터레이터
.. 제너레이터
.. 제너레이터 표현식
. 표준 라이브러리 둘러보기
.. 운영 체제 인터페이스
.. 파일 와일드카드
.. 명령행 인자
.. 에러 출력 리디렉션과 프로그램 종료
.. 문자열 패턴 매칭
.. 수학
.. 인터넷 액세스
.. 날짜와 시간
.. 데이터 압축
.. 성능 측정
.. 품질 관리
.. 배터리가 포함됩니다
. 표준 라이브러리 둘러보기 — 2부
.. 출력 포매팅
.. 템플릿
.. 바이너리 데이터 레코드 배치 작업
.. 다중 스레딩
.. 로깅
.. 약한 참조
.. 리스트 작업 도구
.. 10진 부동 소수점 산술
. 가상 환경 및 패키지
.. 소개
.. 가상 환경 만들기
.. pip로 패키지 관리하기
. 이제 뭘 하지?
. 대화형 입력 편집 및 히스토리 치환
.. 탭 완성 및 히스토리 편집
.. 대화형 인터프리터 대안
. 부동 소수점 산술: 문제점 및 한계
.. 표현 오류
. 부록
.. 대화형 모드
... 에러 처리
... 실행 가능한 파이썬 스크립트
... 대화형 시작 파일
... 커스터마이제이션 모듈