= Turinc machine

== 개요

튜링 머신은 수학자 Alan Turing이 1939년에 제시한 개념으로 계산하는 기계의 일반적인 개념을 설명하기 위한 가상의 기계이며 automata의 일종이다. 튜링은 이 개념을 automatic에서 따온 a-machione이라고 불렀는데 튜링이 죽은 후 창시자의 이름을 따 튜링 머신이라고 부른다.

=== Automata

**오토마타** 는 계산 능력이 있는 추상 기계를 말한다. 계산 능력(Computational ability)이 있는 추상 기계(Abstractional machine)와 그 기계를 풀 수 있는 문제들에 대해 학문적으로 접근한 컴퓨터 과학의 이론 분야를 오토마타 이론(Automata theory)라고 부른다. **오토마타 이론**은 컴퓨터 구조, 컴파일러 설계, 파싱, 정형화 등에 있어서 중요한 이론이다.

오토마타 이론은 쉽게 생각하면 복잡한 기계장치를 간단한 수학 모형으로 만들고, 함수에 들어가는 파라미터와 반환 값, 함수의 구조를 만드는 이론이다.

==== Automaton

오토마타의 단수로, 사람이 행하는 어떤 목적에 합당한 약간 복잡한 동작을 기계적인 컨트롤에 의해 실시하는 장치를 말한다. 외부에서의 조작 없이 스스로 동작하는 기계, 기계에 의헤 조작되는 다른 기계, 동물, 자동 장치등을 말하며, 수학적으로 추상화된 등식 개념을 상징적으로 이를 때, 생물의 구조를 기계적으로 해석할 때 쓰이는 경우도 있다. 

수학적으로 추상화된 개념으로 쓰이이며, 자동화된 기계를 기능적인 견지에서 모델화하여 외부로부터의 입력애 대응하여 내부의 상태가 변화하고, 그리고 신호 또는 동작의 형태로 외부에 출력하는 것으로 보고 이를 오토마톤 또는 오토마타라고 부른다.

이런 개념은 특히 컴퓨터 같은 계산 기계들을 설명하는데 큰 도움이 되며, 컴퓨터 공학의 기초가 된다. 튜링 머신 역시 오토마톤의 일종이다. 오토마톤이 가지는 여러 상태(state)들은 컴퓨터에서 일종의 프로그램에 해당하며, 어떤 상태에서 다른 상태로 바뀌는 것, 즉 프로그램의 실행을 전이(translation)라고 부른다. 오토마톤 중 유한개의 상태를 가지고 있는 것을 유한 상태 기계(Finite State Machine, FSM)이라고 부른다.

==== 오토마타 동작 방식

입력은 유한한 문자열로 주어진다. 오토마타는 유한한 내부 상태를 가지며 무한한 저장 공간을 가질 수도 있다. 저장공간은 다양한 형태로 주어질 수도 있고 이것에 따라서 오토마타의 종류가 나뉜다. 오토마타는 한 번에 하나의 입력 문자열을 읽을 수 있다. 

이때 읽은 문자와 현재의 내부 상태, 그리고 저장공간에 적힌 값에 따라 다음의 내부 상태가 바뀐다. 이 과정에서 저장공간에 적힌 값을 바꿀 수 있다. 이런 과정을 입력 문자열이 다 떨어지거나 또는 종료를 의미하는 내부 상태에 이르면 멈춘다.

오토마타의 내부상태 중에는 승인 상태라고 부르는 것들이 있다. 오토마타가 동작을 멈추었을 때 승인 상태에 있다면 이 오토마타는 그때의 입력 문자열을 '인식'한 것이다. 어떤 문자열을 인식하느냐 인식하지 않느냐를 결정흐므로 하나의 오토마타는 그 문자열을 인식하는 것, 인식하지 않는 것으로 구분하는 '문제를 푼다'라고 할 수 있다. 어떤 문제를 풀 수 있느냐가 오토마타의 능력이 된다. 

비결정적 오토마타에서는 각 동작마다 유한한 가지의 분기점으로 갈 수 있다. 각 분기점마타 다시 분기점으로 갈 수 있다. 그리고 하나의 분기점에서라도 오토마타가 인식을 한다면 이것은 인식한 것으로 간주한다. 즉, 한번에 여러 개의 경우우의 수를 한 꺼번에 해볼 수 있다. 

== 구성

튜링 머신은 아래와 같은 장치로 이루어진다. 

* 테이프(Tape) +
일정한 크기의 셀(cell)로 나뉘어 있는 종이 테이프. 각 셀에는 기호가 기록되어 있으며 길이는 무한히 늘어날 수 있다.
* 헤드(Head) +
종이 테이프의 특정 한 셀을 읽을 수 있는 헤드, 헤드는 고정되어 있고 테이프가 이동한다. 또는 헤드가 움직일 수도 있다.
* 상태 기록기(State register) +
현재 튜링 머신의 상태를 기록하고 있는 장치
** 개시 상태(Start state): 상태 기록기가 초기화된 상태를 의미
** 종료 상태(Halt state): 수행이 종료된 상태
* 행동표(Action table, transition table of instructions) +
특정 상태에서 특정 기호를 읽었을 때 해야 할 행동을 지시한다. 
** 기호를 지우거나 고쳐쓴다.
** 헤드를 오른쪽, 왼쪽으로 한 칸 움직이거나 그 자리에 머문다.
** 상태를 변경한다. 가은 상태에 머무를 수도 없다.

튜링 머신에서 종이 테이프에 기록될 수 있는 기호 및 튜링 머신의 상태와 행동표의 개수는 모두 유한해야 하며 서로 구분되어야 한다.

== Turing 6 primitives

아래 6개의 요소는 기본적으로 모든 것이든 프로그래밍 할 수 있다는 것을 의미한다. 

1. Right: 머신의 head를 현재 사각형의 오른쪽으로 이동
2. Left: 머신의 head를 현재 사각형의 왼쪽으로 이동
3. Print: 현재 사각형의 기호를 프린트
4. Scan: 현재 사각형의 기호를 식별
5. Erase: 현재 사각형의 모든 기호를 지움
6. Halt: 아무것도 하지 않음

