= Module 03: 문자열 조작, 추측 및 확인, 근사치, 이등분

좋습니다 여러분, 시작해 보겠습니다. 좋은 오후입니다. 그럼 이번이 6.0001과 600의 3번째 강의입니다. 늘 그렇듯이 슬라이드와 코드를 다운받아 따라오시기 바랍니다.

그럼 지난번에 우리가 한 일을 간단히 요약해 보겠습니다. 지난번에 우리는 문자열을 새로운 객체 유형, 즉 문자 시퀀스로 이야기했습니다. 그리고 조금 더 복잡한 프로그램을 작성할 수 있는 두 가지 새로운 개념을 도입했습니다.

그래서 우리는 if, elif, else라는 키워드를 사용하여 분기를 도입했습니다. 그리고 분기를 통해 우리는 프로그래머로서 프로그램에 결정을 내릴 수 있는 프로그램을 작성할 수 있었습니다. 그런 다음 두 가지 다른 종류의 루프인 while 루프와 for 루프를 소개했습니다. 그리고 이는 또한 우리 프로그램에 약간의 복잡성을 추가했습니다.

오늘은 문자열에 대해 조금 더 이야기해보겠습니다. 따라서 문자열과 문자열 개체에 대해 수행할 수 있는 몇 가지 작업을 더 살펴보겠습니다. 그런 다음 세 가지 다른 알고리즘인 추측 및 확인 알고리즘, 근사해 알고리즘, 이분법 알고리즘에 대해 이야기하겠습니다.

그럼 바로 들어가 보겠습니다. 먼저 문자열에 대해 조금 이야기하겠습니다. 그래서 문자열은 지난 강의에서 작성한 프로그램에서 보았듯이 대소문자를 구분하는 문자의 시퀀스로 생각했습니다. 그리고 문자열은 객체입니다. 그리고 문자열 개체에 대해 동일한지, 작은지, 큰지 테스트하는 등 이러한 모든 작업을 수행할 수 있습니다.

우리는 단지 두 개의 문자열을 연결하거나 이들에 대한 작은 테스트를 수행하는 것 이상의 일을 할 수 있다는 것이 밝혀졌습니다. 이제 함수나 프로시저에 대한 아이디어를 소개하기 시작하겠습니다. 그리고 다음 강의에서는 함수에 대해 더 자세히 알아보고 자신만의 함수를 작성하는 방법을 알아보겠습니다.

하지만 오늘은, 함수를 사용자를 위해 무언가를 수행하는 일종의 프로시저로 생각할 수 있습니다. 누군가 이미 이 글을 썼습니다. 그래서 우리가 살펴볼 첫 번째 기능은 꽤 인기 있는 기능입니다.

== STRINGS

* 대소문자가 구분되는 문자(characters)의 순서로 생각할 수 있음
* ==, >, < 등으로 비교할 수 있음
* `len()` 은 괄호안의 string의 길이를 알아내는데 사용하는 함수

[source, python]
----
s = "abc"
len(s) -> 3을 계산함
----

그리고 문자열에 적용하면 len이라는 이 함수가 문자열의 길이를 알려줍니다. 그러면 문자열에 몇 개의 문자가 있는지 알려줄 것입니다. 그리고 문자는 문자열에 몇 개의 문자가 있는지 알려주는 것입니다. 문자는 문자, 숫자, 특수 문자, 공백 등이 될 것입니다. 따라서 문자열에 몇 개의 문자가 있는지 계산할 것입니다.

따라서 문자열 s가 "abc"와 같다면 -- 문자열이 따옴표 안에 있다는 것을 기억하세요 -- 그러면 제가 이렇게 하면, 여기서 len s라는 표현식을 쓰면 표현식이기 때문에 값. 따라서 특정 값으로 평가됩니다. 그리고 정의에 따르면 문자열의 길이가 얼마인지 알려줄 것입니다. 길이는 3자입니다.

문자열에 대해 할 수 있는 또 다른 일은 문자열이 일련의 문자이기 때문에 특정 위치에 어떤 문자가 있는지 알고 싶을 수도 있다는 것입니다. 그래서 우리는 인덱싱이라는 멋진 단어를 사용하여 이 작업을 수행합니다. 그러나 문자열에 대한 인덱싱이 의미하는 바는 파이썬에게 찌르기 내부의 특정 위치 또는 특정 인덱스에 있는 문자를 알고 싶다고 말하는 것입니다.

다시 한 번 이 문자열을 사용해 보겠습니다. s는 "abc"와 같습니다. 그리고 그것을 색인화해 봅시다. 따라서 컴퓨터 과학에서는 관례에 따라 0부터 시작합니다. 이 클래스에는 문제 세트 0이 있었습니다. 파이썬도 다르지 않습니다.

